spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/pavels
    username: postgres
    password: s9td3ixh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    url: /openapi.yml
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8085
