services:
  postgres:
    image: postgres:16
    container_name: pavels-postgres
    environment:
      POSTGRES_DB: pavels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s9td3ixh
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
